### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ericlesaquiles**
Update the README so as to refer to euslisp test informations.

### CODE REVIEW

**Comment by ericlesaquiles** [comment]
sorry i didn't PR earlier, btw

**Review by Affonso-Gui — APPROVED** [review]

**Comment by ericlesaquiles** [comment]
some comments: i guess this [blog post]https://ericlesaquiles.github.io/euslisp/2018/08/12/End-of-GSoC-Project.html) is mostly ok as a submission for the gsoc people.

about the conditions and the lambda list, i'm still churning out code. i got tangled in a kind of mess trying to make it more manageable like, so it might be better to make the evaluation (if you haven't yet) without it (i will still do it, this is mostly a time adequacy comment

**Comment by Affonso-Gui** [comment]
No need to hurry about the conditions and lambda list. If you do not have time to complete it you can also submit the way it is, we will find some use for it.

@k-okada Have you seen the blog post?

**Comment by k-okada** [comment]
yes ,https://ericlesaquiles.github.io/ is ok for me

**Comment by ericlesaquiles** [comment]
i prefer to send only what is usable (sadly, it is too little) [45](https://github.com/euslisp/ansi-test/pull/45).. i'm afraid sending other stuff would be more confusing than helpful for now. when it is usable, i'll send it (though probabbly with less functionalities than i wanted)

**Pull request merged**
